name: Build VSCode Web

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: vscode_source

env:
  BUILD_VERSION: 1.18.1
  DOCKERHUB_REPO: letsdone/vscode-web
  
jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout Dockerfile
      uses: actions/checkout@master
      with:
        path: vscode_dockerfile
    
    - name: Download VSCode Source
      env:
          GIT_TERMINAL_PROMPT: 1
      uses: actions/checkout@master
      with:
          repository: microsoft/vscode
          ref: ${{env.BUILD_VERSION}}
          path: vscode_source

    - name: Copy Dockerfile
      run: cp ../vscode_dockerfile/Dockerfile .
          
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build and Push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./vscode_source
        file: ./vscode_source/Dockerfile
        push: true
        platforms: |
          linux/amd64
          linux/arm64
          linux/arm/v7
        tags: |
          ${{ env.DOCKERHUB_REPO }}:latest
          ${{ env.DOCKERHUB_REPO }}:${{ env.BUILD_VERSION }}
     
